@startuml
left to right direction
actor "Cliente" as c
actor "Administrador" as a

rectangle Estudio_Tatuajes {
  usecase "Registrarse" as UC0
  usecase "Navegar Aplicacion" as UC1
  usecase "Chatear" as UC20
  usecase "Pedir Citas" as UC2
  usecase "Comprar Productos" as UC3
  usecase "Gestionar Citas" as UC4
  usecase "Eliminar Citas" as UC4.1
  usecase "Actualizar Citas" as UC4.2

  usecase "Gestionar la aplicación" as UC8
  usecase "Gestionar Empleados" as UC9
  usecase "Actualizar Productos" as UC10.1
  usecase "Eliminar Productos" as UC10.2
  usecase "Gestionar Productos" as UC10
}
c --> UC1
c --> UC2
c --> UC3
c --> UC20
UC2 <.. UC0
c --> UC4


UC3 <.. UC0
UC4 <-- UC4.1
UC4 <-- UC4.2


a --> UC8
a --> UC9
a --> UC10

UC10 <-- UC10.1
UC10 <-- UC10.2


@enduml